#! /bin/sh

sxhkd &

bspc monitor HDMI-A-0 -d boop 
bspc monitor DisplayPort-2 -d term ff vidya discord 
bspc monitor DisplayPort-1 -d twitch bonus meme x

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam desktop='^4'
bspc rule -a discord desktop='^5'
bspc rule -a mpv state=floating
bspc rule -a Browser desktop='^3'
bspc rule -a Screenkey manage=off
